apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    name: api-deployment
    app: htx-back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
      app: htx-back-end
  template:
    metadata:
      labels:
        name: api
        app: htx-back-end
    spec:
      containers:
        - name: api
          image: back-end-api:1.0.0
          env:
            - name: HTTP_PORT
              value: '3000'
            - name: TCP_PORT
              value: '3001'
            - name: NATS_URL
              value: 'nats://nats:4222'
            - name: POSTGRES_HOST
              value: 'postgres-service'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              value: 'postgres'
            - name: POSTGRES_USERNAME
              value: 'postgres'
            - name: POSTGRES_PASSWORD
              value: 'postgres'
            - name: POSTGRES_SYNCHRONIZE
              value: 'false'
            - name: POSTGRES_MAX_POOL_SIZE
              value: '2'
            - name: JWT_SECRET
              value: 'some-secret-value'
            - name: JWT_EXPIRATION
              value: '365'
            - name: OTP_SECRET
              value: 'some-secret-otp-value'
            - name: OTP_EXPIRATION
              value: '20'
            - name: REDIS_URL
              value: 'redis://redis-service:6379'
            - name: ANONYMOUS_MINUTE_LIMIT
              value: '3000'
            - name: ANONYMOUS_FIVE_SECOND_LIMIT
              value: '1000'
            - name: GLOBAL_MINUTE_LIMIT
              value: '10000'
            - name: GLOBAL_SECOND_LIMIT
              value: '1000'
            - name: LATEST_SUPPORTED_FRONTEND_VERSION
              value: '0.26.0-SNAPSHOT'
            - name: MINIMUM_SUPPORTED_FRONTEND_VERSION
              value: '0.23.0'
            - name: FRONTEND_REPO_URL
              value: 'https://github.com/hashgraph/hedera-transaction-tool/releases/download'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
    app: htx-back-end
spec:
  selector:
    name: api
    app: htx-back-end
  ports:
    - name: 'tcp'
      port: 3001
      protocol: TCP
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: api-http-service
  labels:
    name: api-http-service
    app: htx-back-end
spec:
  selector:
    name: api
    app: htx-back-end
  ports:
    - name: 'http'
      port: 3000
      protocol: TCP
      targetPort: 3000
  type: NodePort
